# Generated by Django 5.0.1 on 2024-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_register',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/profile-icon.jpeg', upload_to='profile_pics'),
        ),
    ]
