# Generated by Django 5.0.1 on 2024-02-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_tbl_register_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_jobdetails',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tbl_user_apply_job',
            name='job',
        ),
        migrations.RemoveField(
            model_name='tbl_notification',
            name='application',
        ),
        migrations.RemoveField(
            model_name='tbl_userresume',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_userresume2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_user_apply_job',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_user_apply_job',
            name='resume',
        ),
        migrations.DeleteModel(
            name='tb_skill',
        ),
        migrations.DeleteModel(
            name='tbl_jobdetails',
        ),
        migrations.DeleteModel(
            name='tbl_notification',
        ),
        migrations.DeleteModel(
            name='tbl_userresume',
        ),
        migrations.DeleteModel(
            name='tbl_register',
        ),
        migrations.DeleteModel(
            name='tbl_user_apply_job',
        ),
        migrations.DeleteModel(
            name='tbl_userresume2',
        ),
    ]
