# Generated by Django 5.0.1 on 2024-02-22 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumeapp', '0003_remove_tbl_jobdetails_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('uname', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('plc', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(default='profile_pics/profile-icon.jpeg', upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_jobdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100, verbose_name='jobtitle')),
                ('jobtype', models.CharField(max_length=100, verbose_name='jobtype')),
                ('jobvacancy', models.CharField(max_length=100, verbose_name='jobvacancy')),
                ('jobdate1', models.DateField()),
                ('jobdate2', models.DateField()),
                ('jobexp1', models.CharField(max_length=100, verbose_name='jobexp1')),
                ('jobexp2', models.CharField(max_length=100, verbose_name='jobexp2')),
                ('joblocation', models.CharField(max_length=100, verbose_name='joblocation')),
                ('jobskills', models.CharField(default='', max_length=1000)),
                ('jobdescription', models.CharField(max_length=1000, verbose_name='jobdescription')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tb_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=100)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user_apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('notification_sent', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.tbl_jobdetails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.tbl_user_apply_job')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userresume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100, verbose_name='experience')),
                ('resume', models.ImageField(default='null.jpeg', upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userresume2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100, verbose_name='experience')),
                ('resume', models.ImageField(default='null.jpeg', upload_to='resumes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.tbl_register')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_user_apply_job',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.tbl_userresume2'),
        ),
    ]
