# Generated by Django 5.0.1 on 2024-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_register',
            name='profile_pic',
            field=models.ImageField(upload_to='resumes'),
        ),
    ]
