# Generated by Django 5.0.1 on 2024-02-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0006_alter_tbl_register_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_userresume2',
            name='resume',
            field=models.ImageField(default='null.jpeg', upload_to='file'),
        ),
    ]
