# Generated by Django 5.0.1 on 2024-02-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0007_alter_tbl_userresume2_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_userresume2',
            old_name='resume',
            new_name='resume1',
        ),
    ]
