# Generated by Django 5.0.1 on 2024-02-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0008_rename_resume_tbl_userresume2_resume1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_userresume2',
            name='resume1',
            field=models.ImageField(default='null.jpeg', upload_to='file/file1'),
        ),
    ]
