# Generated by Django 5.0.1 on 2024-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0009_alter_tbl_userresume2_resume1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_userresume',
            name='resume',
            field=models.ImageField(default='null.jpeg', upload_to='resume'),
        ),
    ]
