# Generated by Django 6.0.5 on 2026-05-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0010_alter_tbl_userresume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_skill',
            name='skill',
            field=models.TextField(),
        ),
    ]
