# Generated by Django 6.0.5 on 2026-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0011_alter_tb_skill_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user_apply_job',
            name='status',
            field=models.CharField(default='applied', max_length=100),
        ),
    ]
