# Generated by Django 6.0.5 on 2026-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0012_alter_tbl_user_apply_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_userresume',
            name='resume',
            field=models.ImageField(upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='tbl_userresume2',
            name='resume1',
            field=models.FileField(upload_to='file/file1/'),
        ),
    ]
