# Generated by Django 6.0.5 on 2026-05-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0013_alter_tbl_userresume_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_userresume',
            name='resume',
            field=models.FileField(upload_to='resume'),
        ),
    ]
