# Generated by Django 6.0.5 on 2026-09-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0014_alter_tbl_userresume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_register',
            name='adrs',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='phn',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='pswd',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='utype',
            field=models.CharField(default='', max_length=20),
        ),
    ]
